[theme]
primaryColor = "#6366f1"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e1b4b"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "developer"

[logger]
level = "info"

[server]
maxUploadSize = 200
enableXsrfProtection = true
headless = true
runOnSave = true

[ui]
hideTopBar = false
hideFooterMargins = false
